@startuml
|User|
|Frontend|
start
:Input email;
:Validate email;
:Send POST request;
|Backend|
if (Valid email) then (no)
   :Error response;
   stop
else (yes)
  :Check email;
endif
:Generate single-use token by password field;
:Send link via mail to reset password;
stop

|User|
start
:Open link from email;
|Frontend|
:Input new password;
:Validate new password;
:Send PATCH request with token header;
|Backend|
if (Valid token and new password) then (yes)
    :Extract id and password from token;
      if(Query user by id and Compare password
        from db with password in jwt payload) then (equal)
        :Hash new password;
        :Store new password;
      else (not equal)
        :Error response;
        stop
      endif
else (no)
   :Error response;
   stop
endif
|Frontend|
if (Error response) then (yes)
   :Error state form;
else (no)
  :Redirect to login page;
endif
stop
@enduml
